### ISSUE TITLE
Binder: Error loading mariobuikhuizen/ipyvuetify/master

### ISSUE THREAD

**Issue by filipre** [widgetti/ipyvuetify#245]
Hello!

The binder does not seem to work for the example: https://mybinder.org/v2/gh/mariobuikhuizen/ipyvuetify/master?filepath=examples%2FExamples%20template.ipynb

```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockeris7dzx48'...
HEAD is now at 0b74c45 chore: cleanup and format setup.py
Building conda environment for python=3.7
Using PythonBuildPack builder
Building conda environment for python=3.7
Building conda environment for python=3.7
Step 1/51 : FROM buildpack-deps:bionic
 ---> 8ec5bb581fc6
Step 2/51 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 43d60e6382e7
Step 3/51 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends locales > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> d3cb8332e47e
Step 4/51 : RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen &&     locale-gen
 ---> Using cache
 ---> 200451a06b29
Step 5/51 : ENV LC_ALL=en_US.UTF-8     LANG=en_US.UTF-8     LANGUAGE=en_US.UTF-8
 ---> Using cache
 ---> 41d517ca8ade
Step 6/51 : ENV SHELL=/bin/bash
 ---> Using cache
 ---> 509fa4b3dbce
Step 7/51 : ARG NB_USER
 ---> Using cache
 ---> e3a63a1fdc8c
Step 8/51 : ARG NB_UID
 ---> Using cache
 ---> 094b036510a7
Step 9/51 : ENV USER=${NB_USER}     HOME=/home/${NB_USER}
 ---> Using cache
 ---> 35eda80fff44
Step 10/51 : RUN groupadd         --gid ${NB_UID}         ${NB_USER} &&     useradd         --comment "Default user"         --create-home         --gid ${NB_UID}         --no-log-init         --shell /bin/bash         --uid ${NB_UID}         ${NB_USER}
 ---> Using cache
 ---> 4c065dd4d3d0
Step 11/51 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends        less        unzip        > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> ed575c1e9bef
Step 12/51 : EXPOSE 8888
 ---> Using cache
 ---> ac44bcf947c8
Step 13/51 : ENV APP_BASE=/srv
 ---> Using cache
 ---> 547d1219975f
Step 14/51 : ENV CONDA_DIR=${APP_BASE}/conda
 ---> Using cache
 ---> edf689e92cf2
Step 15/51 : ENV NB_PYTHON_PREFIX=${CONDA_DIR}/envs/notebook
 ---> Using cache
 ---> e28ca7bbc29c
Step 16/51 : ENV NPM_DIR=${APP_BASE}/npm
 ---> Using cache
 ---> 47f6626c6c90
Step 17/51 : ENV NPM_CONFIG_GLOBALCONFIG=${NPM_DIR}/npmrc
 ---> Using cache
 ---> 32287cd4b3ad
Step 18/51 : ENV NB_ENVIRONMENT_FILE=/tmp/env/environment.lock
 ---> Using cache
 ---> b07dbf8ac51e
Step 19/51 : ENV MAMBA_ROOT_PREFIX=${CONDA_DIR}
 ---> Using cache
 ---> ea878ccb1008
Step 20/51 : ENV MAMBA_EXE=${CONDA_DIR}/bin/mamba
 ---> Using cache
 ---> 7d6601cd6ce4
Step 21/51 : ENV CONDA_PLATFORM=linux-64
 ---> Using cache
 ---> f40d8315142d
Step 22/51 : ENV KERNEL_PYTHON_PREFIX=${NB_PYTHON_PREFIX}
 ---> Using cache
 ---> a1805333a060
Step 23/51 : ENV PATH=${NB_PYTHON_PREFIX}/bin:${CONDA_DIR}/bin:${NPM_DIR}/bin:${PATH}
 ---> Using cache
 ---> 2262e70c16c2
Step 24/51 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e10-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2factivate-2dconda-2esh-44e764 /etc/profile.d/activate-conda.sh
 ---> Using cache
 ---> 3e9f20028ad4
Step 25/51 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e10-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2fenvironment-2epy-2d3-2e7-2dlinux-2d64-2elock-27f2b2 /tmp/env/environment.lock
 ---> Using cache
 ---> ae2607b85cc0
Step 26/51 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e10-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2finstall-2dbase-2denv-2ebash-e5509f /tmp/install-base-env.bash
 ---> Using cache
 ---> b5774dd2b742
Step 27/51 : RUN TIMEFORMAT='time: %3R' bash -c 'time /tmp/install-base-env.bash' && rm -rf /tmp/install-base-env.bash /tmp/env
 ---> Using cache
 ---> 2cb05899bfe8
Step 28/51 : RUN mkdir -p ${NPM_DIR} && chown -R ${NB_USER}:${NB_USER} ${NPM_DIR}
 ---> Using cache
 ---> 7c06f07fd02a
Step 29/51 : USER root
 ---> Using cache
 ---> f7fa0a6e882b
Step 30/51 : ARG REPO_DIR=${HOME}
 ---> Using cache
 ---> b5b14538fc97
Step 31/51 : ENV REPO_DIR=${REPO_DIR}
 ---> Using cache
 ---> 1057cb3fe4e9
Step 32/51 : RUN if [ ! -d "${REPO_DIR}" ]; then         /usr/bin/install -o ${NB_USER} -g ${NB_USER} -d "${REPO_DIR}";     fi
 ---> Using cache
 ---> 0a139ab4848c
Step 33/51 : WORKDIR ${REPO_DIR}
 ---> Using cache
 ---> 05117f89bd43
Step 34/51 : RUN chown ${NB_USER}:${NB_USER} ${REPO_DIR}
 ---> Using cache
 ---> 515d98f4d929
Step 35/51 : ENV PATH=${HOME}/.local/bin:${REPO_DIR}/.local/bin:${PATH}
 ---> Using cache
 ---> 3e9481ee9243
Step 36/51 : ENV CONDA_DEFAULT_ENV=${KERNEL_PYTHON_PREFIX}
 ---> Using cache
 ---> 6a5822c66418
Step 37/51 : COPY --chown=1000:1000 src/requirements.txt ${REPO_DIR}/requirements.txt
 ---> 806f3b827db6
Step 38/51 : USER root
 ---> Running in 0b5faf95b735
Removing intermediate container 0b5faf95b735
 ---> 45e899c113f8
Step 39/51 : COPY --chown=1000:1000 src/ ${REPO_DIR}/
 ---> 1c1873d978b7
Step 40/51 : USER ${NB_USER}
 ---> Running in ee6ada009daa
Removing intermediate container ee6ada009daa
 ---> 5236cbd749c4
Step 41/51 : RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"
 ---> Running in d75488d503d8
Collecting pandas
  Downloading pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 43.4 MB/s eta 0:00:00
Collecting numpy>=1.17.3
  Downloading numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 131.1 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.7.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas->-r requirements.txt (line 1)) (2022.7.1)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas->-r requirements.txt (line 1)) (1.16.0)
Installing collected packages: numpy, pandas
Successfully installed numpy-1.21.6 pandas-1.3.5
Removing intermediate container d75488d503d8
 ---> cae84abb785d
Step 42/51 : RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir .
 ---> Running in 8d47db52d6e0
Processing /home/jovyan
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): still running...
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [144 lines of output]
      running egg_info
      running generate_source
      npm WARN old lockfile
      npm WARN old lockfile The package-lock.json file was created with an old version of npm,
      npm WARN old lockfile so supplemental metadata must be fetched from the registry.
      npm WARN old lockfile
      npm WARN old lockfile This is a one-time fix-up, please be patient...
      npm WARN old lockfile
      npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
      npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
      npm WARN deprecated source-map-resolve@0.5.2: See https://github.com/lydell/source-map-resolve#deprecated
      npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
      npm WARN deprecated chokidar@2.1.5: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
      
      added 161 packages, and audited 162 packages in 38s
      
      10 vulnerabilities (1 low, 7 high, 2 critical)
      
      To address all issues, run:
        npm audit fix
      
      Run `npm audit` for details.
      npm notice
      npm notice New major version of npm available! 8.19.2 -> 9.5.1
      npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.5.1>
      npm notice Run `npm install -g npm@9.5.1` to update!
      npm notice
      running jsdeps
      8.19.2
      8.19.2
      Installing build dependencies with npm.  This may take a while...
      npm WARN old lockfile
      npm WARN old lockfile The package-lock.json file was created with an old version of npm,
      npm WARN old lockfile so supplemental metadata must be fetched from the registry.
      npm WARN old lockfile
      npm WARN old lockfile This is a one-time fix-up, please be patient...
      npm WARN old lockfile
      npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
      npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
      npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
      npm WARN deprecated chokidar@2.1.5: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
      npm WARN deprecated source-map-resolve@0.5.2: See https://github.com/lydell/source-map-resolve#deprecated
      npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
      npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
      npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
      npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
      npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
      npm WARN deprecated acorn-dynamic-import@4.0.0: This is probably built in to whatever tool you're using. If you still need it... idk
      npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
      npm WARN deprecated @npmcli/move-file@1.0.1: This functionality has been moved to @npmcli/fs
      npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
      npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
      npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
      npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
      npm WARN deprecated core-js-pure@3.0.1: core-js-pure@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js-pure.
      npm WARN deprecated core-js@3.0.1: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
      
      > jupyter-vuetify@1.8.4 prepare
      > run-s build:*
      
      
      > jupyter-vuetify@1.8.4 build:babel
      > babel src --out-dir lib --copy-files
      
      Browserslist: caniuse-lite is outdated. Please run next command `npm update`
      Successfully compiled 178 files with Babel.
      
      > jupyter-vuetify@1.8.4 build:labextension
      > jupyter labextension build .
      
      Building extension in .
      Browserslist: caniuse-lite is outdated. Please run:
      npx browserslist@latest --update-db
      
      Why you should do it regularly:
      https://github.com/browserslist/browserslist#browsers-data-updating
      
      Compilation starting…
      
      node:internal/crypto/hash:71
        this[kHandle] = new _Hash(algorithm, xofLen);
                        ^
      
      Error: error:0308010C:digital envelope routines::unsupported
          at new Hash (node:internal/crypto/hash:71:19)
          at Object.createHash (node:crypto:133:10)
          at BulkUpdateDecorator.hashFactory (/home/jovyan/js/node_modules/@jupyterlab/builder/node_modules/webpack/lib/util/createHash.js:138:18)
          at BulkUpdateDecorator.update (/home/jovyan/js/node_modules/@jupyterlab/builder/node_modules/webpack/lib/util/createHash.js:44:50)
          at RawSource.updateHash (/home/jovyan/js/node_modules/@jupyterlab/builder/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:64:8)
          at NormalModule._initBuildHash (/home/jovyan/js/node_modules/@jupyterlab/builder/node_modules/webpack/lib/NormalModule.js:737:17)
          at handleParseResult (/home/jovyan/js/node_modules/@jupyterlab/builder/node_modules/webpack/lib/NormalModule.js:801:10)
          at /home/jovyan/js/node_modules/@jupyterlab/builder/node_modules/webpack/lib/NormalModule.js:854:4
          at processResult (/home/jovyan/js/node_modules/@jupyterlab/builder/node_modules/webpack/lib/NormalModule.js:625:11)
          at /home/jovyan/js/node_modules/@jupyterlab/builder/node_modules/webpack/lib/NormalModule.js:676:5 {
        opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
        library: 'digital envelope routines',
        reason: 'unsupported',
        code: 'ERR_OSSL_EVP_UNSUPPORTED'
      }
      
      Node.js v18.12.1
      An error occurred.
      subprocess.CalledProcessError: Command '['node', '/home/jovyan/js/node_modules/@jupyterlab/builder/lib/build-labextension.js', '--core-path', '/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/staging', '/home/jovyan/js']' returned non-zero exit status 1.
      See the log file for details:  /tmp/jupyterlab-debug-ioeuadjp.log
      ERROR: "build:labextension" exited with 1.
      npm ERR! code 1
      npm ERR! path /home/jovyan/js
      npm ERR! command failed
      npm ERR! command sh -c -- run-s build:*
      
      npm ERR! A complete log of this run can be found in:
      npm ERR!     /home/jovyan/.npm/_logs/2023-02-28T08_01_19_742Z-debug-0.log
      rebuilding js and css failed
      missing files: ['/home/jovyan/ipyvuetify/nbextension/extension.js', '/home/jovyan/ipyvuetify/nbextension/index.js']
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/jovyan/setup.py", line 211, in <module>
          "Programming Language :: Python :: 3.10",
        File "/srv/conda/envs/notebook/lib/python3.7/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/srv/conda/envs/notebook/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/srv/conda/envs/notebook/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/srv/conda/envs/notebook/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/srv/conda/envs/notebook/lib/python3.7/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/srv/conda/envs/notebook/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jovyan/setup.py", line 50, in run
          raise e
        File "/home/jovyan/setup.py", line 43, in run
          self.distribution.run_command("jsdeps")
        File "/srv/conda/envs/notebook/lib/python3.7/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/srv/conda/envs/notebook/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jovyan/setup.py", line 124, in run
          stderr=sys.stderr,
        File "/srv/conda/envs/notebook/lib/python3.7/subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Removing intermediate container 8d47db52d6e0
The command '/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir .' returned a non-zero code: 1
```

**Comment by 12rambau** [comment]
just to add to this issue, it would be nice if binder sepcific requirements were moved from the lonely requirements.txt to an extra-requirements in the pyproject.toml

**Comment by mariobuikhuizen** [comment]
I can't find in the docs that binder supports this. Can you point me to the docs?
