### ISSUE TITLE
Vuetify is not properly initialized

### ISSUE THREAD

**Issue by saswatac** [widgetti/ipyvuetify#324]
First, thanks for this very nice package. The widgets work as expected in a jupyterlab notebook environment.

I am developing a jupyterlab extension to open  jupyter-widgets based app in the jupyterlab main shell, with an associated kernel. I I have been able to get ipywidgets widgets to work, but ipyvuewidgets fail when rendering and I see the following error in the browser console - 

```
renderer.ts:77 Error: Vuetify is not properly initialized, see https://vuetifyjs.com/getting-started/quick-start#bootstrapping-the-vuetify-object
    at VueComponent.beforeCreate (VApp.ts:39:13)
    at invokeWithErrorHandling (vue.runtime.common.dev.js:2931:1)
    at callHook$1 (vue.runtime.common.dev.js:3996:1)
    at Vue._init (vue.runtime.common.dev.js:5632:1)
    at new VueComponent (vue.runtime.common.dev.js:5769:1)
    at createComponentInstanceForVnode (vue.runtime.esm.js:4564:1)
    at init (vue.runtime.esm.js:4426:1)
    at createComponent (vue.runtime.esm.js:6591:1)
    at createElm (vue.runtime.esm.js:6545:1)
    at createChildren (vue.runtime.esm.js:6664:1)
```

During the initial page load, I also see the following warning - 

```
console.ts:34 [Vuetify] Multiple instances of Vue detected
See https://github.com/vuetifyjs/vuetify/issues/4068

If you're seeing "$attrs is readonly", it's caused by this
```

How do I initialize vue /vuetify properly?

**Comment by saswatac** [comment]
I was able to get it working, but I am not very sure of the fix. Two different distributions of vue were getting bundled in my jupyterlab build. I was able to avoid it by using singleton=True in my extension package config ( what is referred to here - https://jupyterlab.readthedocs.io/en/latest/extension/extension_dev.html#deduplication-of-dependencies ) and after this change it started working.

we can close the issue for now.
